### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by outsideris**
It is translated with @jukkume, @whiteship and @keesun .

### CODE REVIEW

**Comment by inductor** [comment]
Thank you for your work!
Please fix conflict with LANGS.md, but it can be at last since other languages could be added :)

**Comment by outsideris** [comment]
@keesun @jukkume @whiteship I've done. If you want to review my translation more, I will wait for your work with WIP status on this PR.

**Comment by bagder** [comment]
Excellent work @outsideris!

If you want to, we can merge your work now, announce it to the world and then work on follow-ups as issues/PRs if people find mistakes. Reading the generated outputs is easier for people and when doing that they're also likely to find mistakes or suggest improvements.

I would also like to then add you as "collaborator" on this repository to allow you to merge any korean fixes/PRs that might come.

**Comment by outsideris** [comment]
@bagder Great!! It is better that people review my Korean translation in this repository after merging it.
You can merge it.

**Comment by bagder** [comment]
Lovely!

**Comment by inductor** [comment]
Good job @outsideris :)

**Comment by outsideris** [comment]
@inductor Thank you. :)

**Pull request merged**
