### PR TITLE
Correct sentence in why-ossification.md

### PR DESCRIPTION
**Pull request by QuantumSheep**
This needs verification but the actual sentence is barely understandable (or maybe it's me 😢)

### CODE REVIEW

**Comment by QuantumSheep** [comment]
That's a better sentence but are they really the only primary parties? In the original you said "that are the two primary parties", if their is only one box, doesn't this meant that there is another party?

**Comment by bagder** [comment]
I maintain that the client and the server are the two primary parties involved "in a traditional network data transfer" yes. The others are just "middle-men" of various sorts.

**Comment by QuantumSheep** [comment]
So, maybe "Boxes that sit somewhere between the two end-points and are the primary parties involved in a traditional network data transfer." will match better (without "that" before the "and").

**Comment by QuantumSheep** [comment]
Done!

**Comment by bagder** [comment]
Thanks!

**Pull request merged**
