### PR TITLE
Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by yi-bai**

### CODE REVIEW

**Comment by vastpeng** [comment]
It's cool.

**Comment by g-plane** [comment]
Can you conform this guideline: https://github.com/sparanoid/chinese-copywriting-guidelines ?

**Comment by yi-bai** [comment]
all translations are up to date.

**Comment by bagder** [comment]
Thanks a lot! I've merged it into master now so that we will get outputs generated. I suspect you might notice flaws or mistakes once you read the complete product... =)

**Pull request closed without merging**
