### PR TITLE
German translations of the "Process" section

### PR DESCRIPTION
**Pull request by 5k9m**

### CODE REVIEW

**Comment by inductor** [comment]
@5k9m Is it ok to merge or you want to add more commits?
It'd be a better idea to mention @bagder or me in case you wanted to merge!

**Comment by 5k9m** [comment]
@inductor to tell you the truth, I am not perfectly sure what the policy on this is. Due to the fact that I can only work on these translations irregularly (mostly weekends), I tend to think that pushing these smaller PRs up here might help others to see the progress and join in when I am not working on it. However, as there is - to my knowledge - nobody else working on the german translation, it's quite pointless work ;) 

How would you prefer me to push the next sections? I will try to translate a new section every weekend, as this is when I have time to do so.

**Comment by inductor** [comment]
When I was translating this into Japanese, I asked to merge once some section had been translated. It doesn't have to be perfect since it's an open source repository is my opinion as long as you have the responsibility for what you've done!

You can even send PRs for little fix(like typo). No pressure. Just tell me whenever you wanna merge so we can do that.

**Comment by inductor** [comment]
@5k9m

**Comment by quantumsheep** [comment]
I merged it since the translation in this PR seems to be finished :)

**Comment by bagder** [comment]
thanks team (and yes @inductor I think you're exactly right, early merge is better than waiting for perfection!), I'm on vacation for the moment so I'm slow to respond here. @5k9m, please also add German to the `LANGS.md` file to make it also get rendered and become publicly available. (which then will trigger more help/reports from more users...)

**Comment by quantumsheep** [comment]
> 
> 
> please also add German to the `LANGS.md` file

Done in commit https://github.com/bagder/http3-explained/commit/d241079df2ebf2c333bcd508f51e863ab5416af7

**Comment by bagder** [comment]
Thanks. That looks correct, but gitbook doesn't seem to have generated anything german anyway! :-1:

**Pull request merged**
