### PR TITLE
Add Farsi Translation

### PR DESCRIPTION
**Pull request by kfvahedi**
Sincerely with this Pull Request, I would like to share files I have translated so far and will shortly open another Pull Request as soon as more files are done.

### CODE REVIEW

**Comment by bagder** [comment]
Awesome work @kfvahedi! Since you're the first person here doing it in Farsi, it will make you "the master" of this translation. So would you like us to merge your initial PR right now and thus allow more people to get in and work with you on this? (and possibly report typos etc) Or would you rather wait until you've completed it to some specific level? I'm up for either way, with a small preference in merging as early as possible...

**Comment by kfvahedi** [comment]
Same as you I prefer if we merge it now so more people could help me if interested.
The biggest issue is that RTL languages are not well supported in GitHub and therefore it is difficult to contribute, but fortunately GitBook is supporting RTL in most cases and by keeping the source here, we can finally have the readable format in the book and we’ll only use this repo for further modifications if necessary anytime.

**Comment by bagder** [comment]
Cool, so I merged this now. Thanks! Note that you need to add Farsi to `LANGS.md` to actually have gitbooks render that version.

**Comment by kfvahedi** [comment]
Brilliant, thanks. Alright, I will add it as soon as translation is completed.

**Pull request merged**
