### PR TITLE
fixed grammar

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by kfvahedi** [comment]
I'm not in control of German translation, but AFAIK we do not use articles before adjectives, therefore using "die" before "ähnlich" sounds wrong to me.

**Comment by 0xflotus** [comment]
> I'm not in control of German translation, but AFAIK we do not use articles before adjectives, therefore using "die" before "ähnlich" sounds wrong to me.

The word 'funktioniert' is the key problem of the sentence. Without this verb, I think it would be ok, but with this verb, you need an article at the beginning of the partial sentence. The article 'die' relates to 'Eine Verbindung'.

**Comment by kfvahedi** [comment]
Oh indeed, you're right.

**Comment by 5k9m** [comment]
Sorry about the late reply - jumped into a new job which keeps me a bit busy ;) 

Thanks for your PR, @kfvahedi! It's been merged.
And thanks to @0xflotus for the clarification!

**Comment by kfvahedi** [comment]
The PR was @0xflotus's, I just left a comment, just to collaborate.
Anyway, wishing you the best in your new position, good luck. Cheers ;-)

**Pull request merged**
