### PR TITLE
Add five more files and a missing space

### PR DESCRIPTION
**Pull request by kfvahedi**

### CODE REVIEW

**Comment by bagder** [comment]
"This branch cannot be rebased due to conflicts" seems odd...

**Comment by kfvahedi** [comment]
Yeah it seems odd, I guess GitHub expected me to delete the fork and re-fork it for further contribution :-/

**Comment by bagder** [comment]
No, I don't think so. Most users keep using the same fork for extended periods of time. But I don't know how this happened anyway.

**Comment by kfvahedi** [comment]
Hm ... weird. What do you recommend? :-/

**Comment by bagder** [comment]
First, it appears as if you did this pull request from your master branch. I would strongly discourage that. Work on things in branches instead, never in master.

Then, make sure your master branch is in sync with upstream every once in a while. As you work alone in your own branch, you can then easily rebase that branch onto master (if it lives for a while and master keeps developing). If you rebase a branch that you've already pushed, you need to force-push it next.

**Comment by quantumsheep** [comment]
Seems fixed

**Comment by kfvahedi** [comment]
@bagder Oh thanks for your notes, alright, I'll work on things in another branch of my fork.

@quantumsheep Thanks for your help.

**Pull request merged**
